# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0019_staffadvancetobuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercollection',
            name='Location',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliercollection',
            name='lat',
            field=models.CharField(blank=True, default='0.0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suppliercollection',
            name='lng',
            field=models.CharField(blank=True, default='0.0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoicecollection',
            name='Location',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoicecollection',
            name='lat',
            field=models.CharField(blank=True, default='0.0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoicecollection',
            name='lng',
            field=models.CharField(blank=True, default='0.0', max_length=200, null=True),
        ),
    ]
