# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mamtaApp', '0021_takeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeorder',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
