# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mamtaApp', '0022_takeorder_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeorder',
            name='partyName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
